from turtle import *
#draw a square
begin_fill()
color("darkgreen")
speed(100)
width(6)
penup()
goto(-700, -120)
pendown()
forward(1400)
right(90)
forward(500)
right(90)
forward(1400)
right(90)
forward(500)
end_fill()

#draw a square
begin_fill()
penup()
goto(-700, -120)
pendown()
color("navy")
right(90)
forward(1400)
left(90)
forward(500)
left(90)
forward(1400)
left(90)
forward(500)
end_fill()

#we want to paint the house
#step 1: draw a square 
begin_fill()
color("dimgrey")
speed(30)
left(90)
penup()
goto(-500, -200)
pendown()
forward(200)
left(90)

forward(200)
left(90)

forward(200)
left(90)

forward(200)
left(90)
end_fill()
# end of square

#drawimg a door
begin_fill()

forward(75)
color("saddlebrown")
left(90)
forward(100)  #height of the door
right(90)
forward(50)
right(90)
forward(100)

end_fill()
penup()
goto(-300, 0)
pendown()

color("black")
begin_fill()
right(150)
forward(200)
left(120)
forward(200)

end_fill()





#drawing a window
begin_fill()
color("cornflowerblue")
penup()
goto(-470, -30)
pendown()
left(30)
forward(50)
left(90)
forward(50)
left(90)
forward(50)
left(90)
forward(50)
end_fill()
  
#adjusting the window

color("black")
right(180)

forward(50)
right(90)
forward(50)
right(90)

forward(50)
right(90)
forward(50)
right(90)

forward(25)
right(90)
forward(50)
penup()
goto(-470, -55)
pendown()
left(90)
forward(50)


#drawing the 2nd window
begin_fill()
color("cornflowerblue")
penup()
goto(-380, -30)
pendown()

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)
end_fill()

#adjusting the 2nd window

color("black")

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)

forward(25)
right(90)
forward(50)
penup()
goto(-380, -55)
pendown()
left(90)
forward(50)

#adjusting the 2nd door 
penup()
goto(-425,-200)
pendown()
left(90)
forward(100)
right(90)
forward(50)
right(90)
forward(100)
penup()
goto(-500, -200)
pendown()

width(6)
left(90)
forward(200)
left(90)
forward(200)

left(90)
forward(200)
left(90)
forward(200)

#we want to paint the house
#step 1: draw a square 
begin_fill()
color("sienna")
speed(0)
left(90)
penup()
goto(-200, -200)
pendown()
forward(200)
left(90)

forward(200)
left(90)

forward(200)
left(90)

forward(200)
left(90)
end_fill()
# end of square

#drawimg a door
begin_fill()

forward(75)
color("maroon")
left(90)
forward(100)  #height of the door
right(90)
forward(50)
right(90)
forward(100)

end_fill()
penup()
goto(-0, 0)
pendown()

color("black")
begin_fill()
right(150)
forward(200)
left(120)
forward(200)

end_fill()





#drawing a window
begin_fill()
color("cornflowerblue")
penup()
goto(-170, -30)
pendown()
left(30)
forward(50)
left(90)
forward(50)
left(90)
forward(50)
left(90)
forward(50)
end_fill()
  
#adjusting the window

color("black")
right(180)

forward(50)
right(90)
forward(50)
right(90)

forward(50)
right(90)
forward(50)
right(90)

forward(25)
right(90)
forward(50)
penup()
goto(-170, -55)
pendown()
left(90)
forward(50)


#drawing the 2nd window
begin_fill()
color("cornflowerblue")
penup()
goto(-80, -30)
pendown()

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)
end_fill()

#adjusting the 2nd window

color("black")

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)

forward(25)
right(90)
forward(50)
penup()
goto(-80, -55)
pendown()
left(90)
forward(50)

#adjusting the 2nd door 
penup()
goto(-125,-200)
pendown()
left(90)
forward(100)
right(90)
forward(50)
right(90)
forward(100)
penup()
goto(-200, -200)
pendown()

width(6)
left(90)
forward(200)
left(90)
forward(200)

left(90)
forward(200)
left(90)
forward(200)

#we want to paint the house
#step 1: draw a square 
begin_fill()
color("saddlebrown")
speed(30)
left(90)
penup()
goto(100, -200)
pendown()
forward(200)
left(90)

forward(200)
left(90)

forward(200)
left(90)

forward(200)
left(90)
end_fill()
# end of square

#drawimg a door
begin_fill()

forward(75)
color("darkgoldenrod")
left(90)
forward(100)  #height of the door
right(90)
forward(50)
right(90)
forward(100)

end_fill()
penup()
goto(300, 0)
pendown()

color("black")
begin_fill()
right(150)
forward(200)
left(120)
forward(200)

end_fill()





#drawing a window
begin_fill()
color("cornflowerblue")
penup()
goto(130, -30)
pendown()
left(30)
forward(50)
left(90)
forward(50)
left(90)
forward(50)
left(90)
forward(50)
end_fill()
  
#adjusting the window

color("black")
right(180)

forward(50)
right(90)
forward(50)
right(90)

forward(50)
right(90)
forward(50)
right(90)

forward(25)
right(90)
forward(50)
penup()
goto(130, -55)
pendown()
left(90)
forward(50)


#drawing the 2nd window
begin_fill()
color("cornflowerblue")
penup()
goto(220, -30)
pendown()

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)
end_fill()

#adjusting the 2nd window

color("black")

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)

forward(50)
right(90)

forward(25)
right(90)
forward(50)
penup()
goto(220, -55)
pendown()
left(90)
forward(50)

#adjusting the 2nd door 
penup()
goto(175,-200)
pendown()
left(90)
forward(100)
right(90)
forward(50)
right(90)
forward(100)
penup()
goto(100, -200)
pendown()

width(6)
left(90)
forward(200)
left(90)
forward(200)

left(90)
forward(200)
left(90)
forward(200)

#drawning the moon
penup()
goto(460, 250)
begin_fill()
color("dimgray")
pendown()


color("dimgray")
circle(90)
end_fill()


#drawing stars

penup()
goto(-550, 300)
pendown()
speed(0)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

# drawing star

penup()
goto(-450, 200)
pendown()
speed(100)
begin_fill()
color("gold")


forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
end_fill()

# drawing star

penup()
goto(-600, 150)
pendown()
speed(0)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

# drawing star

penup()
goto(-485, 110)
pendown()
speed(100)
begin_fill()
color("gold")


forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
end_fill()

# drawing star

penup()
goto(-650, 20)
pendown()
speed(100)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

# drawing star

penup()
goto(-560, -25)
pendown()
speed(100)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

#drawing star

penup()
goto(-320, 300)
pendown()
speed(0)
begin_fill()
color("gold")


forward(35)
left(145)
forward(35)
left(145)
forward(35)
left(145)
forward(35)
left(145)
forward(35)
end_fill()

#drawing star

penup()
goto(-180, 250)
pendown()
speed(0)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

#drawing star

penup()
goto(-290, 120)
pendown()
speed(0)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

#drawing star

penup()
goto(-255, 200)
pendown()
speed(0)
begin_fill()
color("gold")


forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
end_fill()

#drawing star

penup()
goto(-30, 315)
pendown()
speed(0)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

#drawing star

penup()
goto(-40, 220)
pendown()
speed(0)
begin_fill()
color("gold")


forward(20)
left(145)
forward(20)
left(145)
forward(20)
left(145)
forward(20)
left(145)
forward(20)
end_fill()

#drawing star

penup()
goto(50, 225)
pendown()
speed(0)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

#drawing star

penup()
goto(15, 130)
pendown()
speed(0)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

#drawing star

penup()
goto(-165, 130)
pendown()
speed(0)
begin_fill()
color("gold")


forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
end_fill()

#drawing star

penup()
goto(135, 145)
pendown()
speed(0)
begin_fill()
color("gold")


forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
end_fill()

#drawing star

penup()
goto(160, 320)
pendown()
speed(0)
begin_fill()
color("gold")


forward(35)
left(145)
forward(35)
left(145)
forward(35)
left(145)
forward(35)
left(145)
forward(35)
end_fill()

#drawing star

penup()
goto(235, 195)
pendown()
speed(0)
begin_fill()
color("gold")


forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
end_fill()

#drawing star

penup()
goto(300, 305)
pendown()
speed(0)
begin_fill()
color("gold")


forward(35)
left(145)
forward(35)
left(145)
forward(35)
left(145)
forward(35)
left(145)
forward(35)
end_fill()

#drawing star

penup()
goto(385, 160)
pendown()
speed(0)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

#drawing star

penup()
goto(275, 95)
pendown()
speed(0)
begin_fill()
color("gold")


forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
end_fill()

#drawing star

penup()
goto(415, 330)
pendown()
speed(0)
begin_fill()
color("gold")


forward(35)
left(145)
forward(35)
left(145)
forward(35)
left(145)
forward(35)
left(145)
forward(35)
end_fill()

#drawing star

penup()
goto(380, 5)
pendown()
speed(0)
begin_fill()
color("gold")


forward(35)
left(145)
forward(35)
left(145)
forward(35)
left(145)
forward(35)
left(145)
forward(35)
end_fill()

#drawing star

penup()
goto(480, 100)
pendown()
speed(0)
begin_fill()
color("gold")


forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
end_fill()

#drawing star

penup()
goto(600, 140)
pendown()
speed(0)
begin_fill()
color("gold")


forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
left(145)
forward(30)
end_fill()

#drawing star

penup()
goto(600, 40)
pendown()
speed(0)
begin_fill()
color("gold")


forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
end_fill()

#drawing star

penup()
goto(530, 0)
pendown()
speed(0)
begin_fill()
color("gold")


forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
left(145)
forward(25)
end_fill()













































































































exitonclick()